name: CI
on: [push]
jobs:
  image_scan:
    name: Build image and run security scan  
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@v1
      with: 
        docker_version: '20.10.7'

    - name: Build Docker image
      run: docker build -f Dockerfile -t pygoat:latest .

    - name: Install Docker Scout
      run: |
        curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
        sh install-scout.sh

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Docker Scout Scan
      run: |
        docker scout quickview
        docker scout cves
